apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signin-api
  namespace: signin-app
  labels:
    app: signin-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: signin-api
