apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signin-app

resources:
  - ../../base

patches:
  # Production-specific patches
  - target:
      kind: Deployment
      name: signin-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Production"

  # Higher resource requests for production
  - target:
      kind: Deployment
      name: signin-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  # Higher HPA thresholds for production
  - target:
      kind: HorizontalPodAutoscaler
      name: signin-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 20

  # Higher PDB for production
  - target:
      kind: PodDisruptionBudget
      name: signin-api
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 3

commonLabels:
  environment: production
